[package]
name = "xoroshiro"
version = "0.1.0"
authors = ["Coda Hale <coda.hale@gmail.com>"]

[dependencies]
rand = "*"

[dev-dependencies.criterion]
git = "https://github.com/japaric/criterion.rs.git"
